<?php
header('Content-Type: application/json');
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: POST");
ini_set('display_errors', 0);

require_once __DIR__ . '/../../secure_config/db_connect.php';

$input = json_decode(file_get_contents('php://input'), true);
$action = $input['action'] ?? '';

try {
    switch ($action) {
        
        // --- 1. ADMIN LOGIN ---
        case 'login':
            $user = $input['username'];
            $pass = $input['password'];
            
            $stmt = $pdo->prepare("SELECT * FROM users WHERE username = ? AND role = 'admin' LIMIT 1");
            $stmt->execute([$user]);
            $account = $stmt->fetch();

            if ($account && password_verify($pass, $account['password_hash'])) {
                echo json_encode(['status' => 'success', 'username' => $account['username']]);
            } else {
                echo json_encode(['status' => 'error', 'message' => 'Invalid Admin Credentials']);
            }
            break;

        // --- 2. DASHBOARD DATA ---
        case 'get_dashboard_data':
            // A. Stats
            $stats = [
                'total_users' => $pdo->query("SELECT COUNT(*) FROM users")->fetchColumn(),
                'active_users' => $pdo->query("SELECT COUNT(*) FROM users WHERE last_login_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)")->fetchColumn(),
                'total_clicks' => number_format($pdo->query("SELECT COUNT(*) FROM clicks")->fetchColumn()),
            ];

            // FIX: Revenue Calculation (Sum of actual money generated by Ad Clicks)
            // If null (no clicks yet), default to 0
            $rawRevenue = $pdo->query("SELECT SUM(revenue_generated) FROM clicks")->fetchColumn();
            $stats['total_revenue'] = number_format($rawRevenue ? $rawRevenue : 0, 2);

            // B. Users List (Latest 10)
            $users = $pdo->query("
                SELECT id, username, email, role, wallet_balance, DATE_FORMAT(created_at, '%Y-%m-%d') as joined,
                (SELECT COUNT(*) FROM links WHERE user_id = users.id) as links_count
                FROM users ORDER BY created_at DESC LIMIT 10
            ")->fetchAll(PDO::FETCH_ASSOC);

            // Format wallet balance for display
            foreach($users as &$u) {
                $u['wallet_balance'] = number_format($u['wallet_balance'], 4);
            }

            // C. Pending Payouts
            $payouts = $pdo->query("
                SELECT p.id, u.username, p.amount, p.method 
                FROM payouts p JOIN users u ON p.user_id = u.id 
                WHERE p.status = 'pending' LIMIT 5
            ")->fetchAll(PDO::FETCH_ASSOC);

            // D. Pending Ads
            $ads = $pdo->query("
                SELECT id, advertiser_name, ad_type, destination_url, is_adult 
                FROM ad_campaigns WHERE status = 'pending_review' LIMIT 5
            ")->fetchAll(PDO::FETCH_ASSOC);

            echo json_encode([
                'status' => 'success',
                'stats' => $stats,
                'users' => $users,
                'payouts' => $payouts,
                'ads' => $ads
            ]);
            break;

        // --- 3. ACTIONS (Approve/Reject) ---
        case 'approve_payout':
            $id = $input['id'];
            $pdo->prepare("UPDATE payouts SET status = 'completed', processed_at = NOW() WHERE id = ?")->execute([$id]);
            echo json_encode(['status' => 'success']);
            break;

        case 'reject_payout':
            $id = $input['id'];
            $stmt = $pdo->prepare("SELECT user_id, amount FROM payouts WHERE id = ?");
            $stmt->execute([$id]);
            $p = $stmt->fetch();
            
            // Refund
            $pdo->prepare("UPDATE users SET wallet_balance = wallet_balance + ? WHERE id = ?")->execute([$p['amount'], $p['user_id']]);
            // Mark rejected
            $pdo->prepare("UPDATE payouts SET status = 'rejected' WHERE id = ?")->execute([$id]);
            echo json_encode(['status' => 'success']);
            break;

        case 'approve_ad':
            $pdo->prepare("UPDATE ad_campaigns SET status = 'active' WHERE id = ?")->execute([$input['id']]);
            echo json_encode(['status' => 'success']);
            break;

        case 'reject_ad':
            $pdo->prepare("UPDATE ad_campaigns SET status = 'rejected' WHERE id = ?")->execute([$input['id']]);
            echo json_encode(['status' => 'success']);
            break;

        default:
            echo json_encode(['status' => 'error', 'message' => 'Invalid Action']);
    }

} catch (Exception $e) {
    echo json_encode(['status' => 'error', 'message' => $e->getMessage()]);
}
?>